name: minima
description: A URL shortening API using Shelf
version: 1.0.0
repository: https://github.com/HughTB/minima-dart

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.1.4
  args: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
